import {
  BookOpen,
  ShieldCheck,
  TrendingUp,
  Palette,
  Scale,
  Atom,
  Plane,
  Zap,
  Brain,
  Code,
  Settings,
  Database,
  PlayCircle,
  Leaf,
  Globe,
  Activity,
  Music,
  Languages,
  Sparkles,
} from "lucide-react";

export const DOMAINS = [
  {
    id: "edu",
    t: "Education",
    d: "Foundational teaching methods and academic excellence.",
    c: "450+ Courses",
    isFree: true,
    subcategories: [
      "Primary Education",
      "Secondary Education",
      "Higher Education",
      "Competitive Exams",
      "Special Education",
      "Teacher Training",
    ],
    icon: BookOpen,
    color: "from-[#6C63FF] to-[#4F46E5]",
  },
  {
    id: "med",
    t: "Medical",
    d: "Health sciences and modern medical research.",
    c: "320+ Courses",
    isFree: true,
    subcategories: [
      "Anatomy",
      "Pharmacology",
      "Surgery",
      "Nursing",
      "Pathology",
      "Pediatrics",
    ],
    icon: ShieldCheck,
    color: "from-[#FFB6FF] to-[#7C4DFF]",
  },
  {
    id: "mgmt",
    t: "Management",
    d: "Leadership and organizational strategy.",
    c: "210+ Courses",
    isFree: true,
    subcategories: [
      "HR Management",
      "Finance",
      "Marketing",
      "Operations",
      "Strategic Management",
      "Entrepreneurship",
    ],
    icon: TrendingUp,
    color: "from-[#00D4FF] to-[#6C63FF]",
  },
  {
    id: "arts",
    t: "Arts & Design",
    d: "Creative expression and visual communication.",
    c: "180+ Courses",
    isFree: true,
    subcategories: [
      "Graphic Design",
      "UI/UX Design",
      "Fine Arts",
      "Fashion Design",
      "Interior Design",
      "Animation",
    ],
    icon: Palette,
    color: "from-[#FACC15] to-[#EAB308]",
  },
  {
    id: "law",
    t: "Law LLB",
    d: "Legal systems and constitutional studies.",
    c: "240+ Courses",
    isFree: true,
    subcategories: [
      "Constitutional Law",
      "Criminal Law",
      "Civil Law",
      "Corporate Law",
      "Intellectual Property",
      "International Law",
    ],
    icon: Scale,
    color: "from-[#6C63FF] to-[#00D4FF]",
  },
  {
    id: "sci",
    t: "Science",
    d: "Exploration of the physical and natural world.",
    c: "290+ Courses",
    isFree: true,
    subcategories: [
      "Physics",
      "Chemistry",
      "Biology",
      "Astronomy",
      "Mathematics",
      "Environmental Science",
    ],
    icon: Atom,
    color: "from-[#4F46E5] to-[#7C4DFF]",
  },
  {
    id: "tour",
    t: "Tourism",
    d: "Global travel and hospitality management.",
    c: "150+ Courses",
    isFree: true,
    subcategories: [
      "Travel Planning",
      "Hospitality Management",
      "Tour Guiding",
      "Ecotourism",
      "Event Management",
      "Destination Marketing",
    ],
    icon: Plane,
    color: "from-[#00D4FF] to-[#4F46E5]",
  },
  {
    id: "skill",
    t: "Skill Development",
    d: "Practical vocational and technical skills.",
    c: "190+ Courses",
    isFree: true,
    subcategories: [
      "Public Speaking",
      "Photography",
      "Time Management",
      "Leadership",
      "Personal Branding",
      "Emotional Intelligence",
    ],
    icon: Zap,
    color: "from-[#FFB6FF] to-[#6C63FF]",
  },
  {
    id: "psych",
    t: "Psychology",
    d: "Human behavior and mental processes.",
    c: "220+ Courses",
    isFree: true,
    subcategories: [
      "Cognitive Psychology",
      "Clinical Psychology",
      "Social Psychology",
      "Child Psychology",
      "Counseling",
      "Behavioral Science",
    ],
    icon: Brain,
    color: "from-[#6C63FF] to-[#4F46E5]",
  },
  {
    id: "it",
    t: "Computer/IT",
    d: "Software engineering and digital systems.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Web Development",
      "Mobile Apps",
      "Cyber Security",
      "AI & ML",
      "Cloud Computing",
      "Data Science",
    ],
    icon: Code,
    color: "from-[#00D4FF] to-[#6C63FF]",
  },
  {
    id: "eng",
    t: "Engineering",
    d: "Technical design and structural innovation.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemical Engineering",
      "Software Engineering",
      "Aerospace Engineering",
    ],
    icon: Settings,
    color: "from-[#FFB6FF] to-[#7C4DFF]",
  },
  {
    id: "comm",
    t: "Commerce",
    d: "Business, finance, and global trade.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Accounting",
      "Economics",
      "Banking",
      "Taxation",
      "Auditing",
      "Business Studies",
    ],
    icon: Database,
    color: "from-[#FACC15] to-[#EAB308]",
  },
  {
    id: "media",
    t: "Media/Reporter",
    d: "Journalism and digital communication.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Journalism",
      "Video Production",
      "Digital Media",
      "Anchoring",
      "Public Relations",
      "Mass Communication",
    ],
    icon: PlayCircle,
    color: "from-[#6C63FF] to-[#00D4FF]",
  },
  {
    id: "agri",
    t: "Agriculture",
    d: "Modern farming and sustainable food systems.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Crop Science",
      "Soil Management",
      "Horticulture",
      "Animal Husbandry",
      "Organic Farming",
      "Agri-Business",
    ],
    icon: Leaf,
    color: "from-[#4F46E5] to-[#7C4DFF]",
  },
  {
    id: "hotel",
    t: "Hotel Management",
    d: "Elite hospitality and service standards.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Front Office",
      "Culinary Arts",
      "Housekeeping",
      "Food & Beverage",
      "Hospitality Law",
      "Resort Management",
    ],
    icon: Globe,
    color: "from-[#00D4FF] to-[#4F46E5]",
  },
  {
    id: "sports",
    t: "Sports & Fitness",
    d: "Physical health and professional athletics.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Yoga & Meditation",
      "Gym Training",
      "Sports Coaching",
      "Nutrition & Diet",
      "Sports Medicine",
      "Athletic Training",
    ],
    icon: Activity,
    color: "from-[#FFB6FF] to-[#6C63FF]",
  },
  {
    id: "perf",
    t: "Performing Arts",
    d: "Music, dance, and theatrical mastery.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "Music Mastery",
      "Choreography",
      "Theatre Arts",
      "Vocal Training",
      "Scriptwriting",
      "Filmmaking",
    ],
    icon: Music,
    color: "from-[#6C63FF] to-[#4F46E5]",
  },
  {
    id: "lang",
    t: "Language Study",
    d: "Global linguistics and cultural communication.",
    c: "Premium",
    isFree: false,
    subcategories: [
      "English",
      "French",
      "German",
      "Spanish",
      "Japanese",
      "Chinese",
      "Sanskrit",
      "Arabic",
    ],
    icon: Languages,
    color: "from-[#00D4FF] to-[#6C63FF]",
  },
  {
    id: "other",
    t: "Other/+",
    d: "Miscellaneous and niche fields of knowledge.",
    c: "Various",
    isFree: false,
    subcategories: [
      "Miscellaneous",
      "Experimental",
      "Niche Topics",
      "General Knowledge",
      "Uncategorized",
    ],
    icon: Sparkles,
    color: "from-[#6B7280] to-[#111827]",
  },
];
