import { createFileRoute } from "@tanstack/react-router";
import {
  HelpCircle,
  Book,
  Languages,
  Beaker,
  Calculator,
  Globe,
  ScrollText,
  Users,
  Search,
  Clock,
  ArrowRight,
  GraduationCap,
} from "lucide-react";
import { useState, useEffect, useMemo } from "react";
import { StudentSidebar } from "@/components/student/StudentSidebar";
import { StudentHeader } from "@/components/student/StudentHeader";
import { db } from "@/lib/firebase";
import { collection, query, orderBy, onSnapshot } from "firebase/firestore";

export const Route = createFileRoute("/student/question-bank")({
  component: StudentQuestionBank,
});

const CLASSES = [
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th",
];
const SUBJECTS = [
  { id: "marathi", name: "Marathi", icon: Languages },
  { id: "hindi", name: "Hindi", icon: Languages },
  { id: "english", name: "English", icon: Book },
  { id: "science", name: "Science", icon: Beaker },
  { id: "maths", name: "Maths", icon: Calculator },
  { id: "geography", name: "Geography", icon: Globe },
  { id: "history", name: "History", icon: ScrollText },
  { id: "civics", name: "Civics", icon: Users },
];

function StudentQuestionBank() {
  const [selectedClass, setSelectedClass] = useState("1st");
  const [selectedSubjectId, setSelectedSubjectId] = useState(SUBJECTS[0].id);
  const [questions, setQuestions] = useState<any[]>([]);
  const [mounted, setMounted] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    setMounted(true);
    const q = query(
      collection(db, "question_bank"),
      orderBy("createdAt", "desc"),
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));
      setQuestions(data);
    });

    return () => unsubscribe();
  }, []);

  const handleDownload = (unitName: string, subjectId: string) => {
    const subject = SUBJECTS.find((s) => s.id === subjectId)?.name || "Subject";
    const filename = `Question_Bank_${subject}_${unitName.replace(" ", "_")}.pdf`;
    const content = `Mock PDF Content for ${subject} ${unitName}\n\nGenerated by Institutional Portal.`;
    const blob = new Blob([content], { type: "application/pdf" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  const filteredData = useMemo(() => {
    return questions.filter((q) => {
      const matchClass = q.class === selectedClass;
      const matchSubject = q.subjectId === selectedSubjectId;
      const matchSearch = q.text
        ?.toLowerCase()
        .includes(searchTerm.toLowerCase());
      return matchClass && matchSubject && matchSearch;
    });
  }, [questions, selectedClass, selectedSubjectId, searchTerm]);

  if (!mounted) return null;

  return (
    <div className="min-h-screen bg-white">
      <StudentHeader />
      <StudentSidebar />

      <main className="lg:pl-64 pt-20 min-h-screen bg-white">
        <div className="p-4 md:p-8 space-y-6 max-w-[1200px] mx-auto">
          <div className="bg-white p-6 border border-[#dee2e6] rounded-md shadow-sm">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
              <div className="flex flex-col gap-1">
                <label className="text-[13px] font-bold text-[#333]">
                  Class
                </label>
                <select
                  value={selectedClass}
                  onChange={(e) => setSelectedClass(e.target.value)}
                  className="w-full h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px] text-[#555] focus:border-[#66afe9] outline-none bg-white transition-all shadow-inner"
                >
                  <option value="">Select</option>
                  {CLASSES.map((c) => (
                    <option key={c} value={c}>
                      {c}
                    </option>
                  ))}
                </select>
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-[13px] font-bold text-[#333]">
                  Semester
                </label>
                <select className="w-full h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px] text-[#555] focus:border-[#66afe9] outline-none bg-white transition-all shadow-inner">
                  <option value="">Select</option>
                  <option value="1">1st Semester</option>
                  <option value="2">2nd Semester</option>
                </select>
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-[13px] font-bold text-[#333]">
                  Subject
                </label>
                <select
                  value={selectedSubjectId}
                  onChange={(e) => setSelectedSubjectId(e.target.value)}
                  className="w-full h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px] text-[#555] focus:border-[#66afe9] outline-none bg-white transition-all shadow-inner"
                >
                  <option value="">Select</option>
                  {SUBJECTS.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <div className="flex justify-center gap-2">
              <button className="px-3 py-1.5 bg-[#198754] text-white rounded-[4px] text-[14px] font-medium hover:bg-[#157347] transition-all border border-[#198754]">
                Search
              </button>
              <button className="px-3 py-1.5 bg-[#dc3545] text-white rounded-[4px] text-[14px] font-medium hover:bg-[#bb2d3b] transition-all border border-[#dc3545]">
                Reset
              </button>
            </div>
          </div>

          <div className="border border-[#dee2e6] rounded-sm overflow-hidden">
            <div className="bg-[#3f19c9] px-4 py-2 border-b border-[#dee2e6]">
              <h2 className="text-white font-bold text-[14px]">
                Question Bank With Solution for Common Branches-1st/2nd Semester
              </h2>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse bg-white">
                <thead>
                  <tr className="border-b border-[#dee2e6] text-[#333] text-[14px] font-bold">
                    <th className="px-4 py-2 border-r border-[#dee2e6] w-16">
                      Sr.No.
                    </th>
                    <th className="px-4 py-2 border-r border-[#dee2e6]">
                      Subject / Topic Name
                    </th>
                    <th className="px-4 py-2 border-r border-[#dee2e6]">
                      Type
                    </th>
                    <th className="px-4 py-2 border-r border-[#dee2e6] w-24">
                      Marks
                    </th>
                    <th className="px-4 py-2">Download file</th>
                  </tr>
                </thead>
                <tbody className="text-[14px] text-[#333]">
                  {filteredData.length > 0 ? (
                    filteredData.map((q, idx) => (
                      <tr
                        key={q.id}
                        className="border-b border-[#dee2e6] hover:bg-slate-50"
                      >
                        <td className="px-4 py-2 border-r border-[#dee2e6] text-center text-[#777]">
                          {idx + 1}
                        </td>
                        <td className="px-4 py-2 border-r border-[#dee2e6] text-[#555] font-medium">
                          {q.text}
                        </td>
                        <td className="px-4 py-2 border-r border-[#dee2e6]">
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${q.type === "Objective" ? "bg-blue-100 text-blue-700" : "bg-purple-100 text-purple-700"}`}
                          >
                            {q.type}
                          </span>
                        </td>
                        <td className="px-4 py-2 border-r border-[#dee2e6] text-center font-bold text-slate-600">
                          {q.marks}
                        </td>
                        <td className="px-4 py-2">
                          <button
                            onClick={() =>
                              handleDownload(`Unit ${idx + 1}`, q.subjectId)
                            }
                            className="text-[#3f19c9] hover:underline font-bold"
                          >
                            Unit {idx + 1}
                          </button>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td
                        colSpan={5}
                        className="px-4 py-12 text-center text-[#999] italic"
                      >
                        No records found for the selected criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          <div className="bg-[#f8f9fa] p-4 border border-[#dee2e6] rounded-md">
            <p className="text-[12px] text-[#666]">
              Note: This question bank is curated for official institutional
              use. Please ensure you are studying the correct unit for your
              semester.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
