import { createFileRoute, Link } from "@tanstack/react-router";
import { motion, AnimatePresence } from "framer-motion";
import {
  HelpCircle,
  Book,
  Languages,
  Beaker,
  Calculator,
  Globe,
  ScrollText,
  Users,
  Plus,
  Send,
  Calendar,
  Clock,
  CheckCircle2,
  Search,
  Filter,
  ArrowRight,
  MoreVertical,
  Trash2,
  Edit3,
  Share2,
  Download,
  MessageCircle,
  Hash,
  GraduationCap,
  ChevronRight,
  Zap,
  Star,
  Trophy,
  Award,
  Rocket,
  ChevronLeft,
  BookOpen,
  FileText,
  Layout,
  ListChecks,
  Sparkles,
  PlusCircle,
} from "lucide-react";
import { TeacherHeader } from "@/components/teacher/TeacherHeader";
import { TeacherSidebar } from "@/components/teacher/TeacherSidebar";
import { useState, useMemo, useEffect } from "react";
import { showToast as toast } from "@/lib/custom-toast";
import { useAuth } from "@/hooks/use-auth";
import { db } from "@/lib/firebase";
import {
  collection,
  addDoc,
  getDocs,
  deleteDoc,
  doc,
  query,
  orderBy,
  onSnapshot,
} from "firebase/firestore";

export const Route = createFileRoute("/teacher/question-bank")({
  component: QuestionBankPage,
});

const CLASSES = [
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th",
];
const SUBJECTS = [
  {
    id: "marathi",
    name: "Marathi",
    icon: Languages,
    color: "bg-pink-500",
    gradient: "from-pink-500 to-rose-600",
  },
  {
    id: "hindi",
    name: "Hindi",
    icon: Languages,
    color: "bg-orange-500",
    gradient: "from-orange-500 to-amber-600",
  },
  {
    id: "english",
    name: "English",
    icon: Book,
    color: "bg-blue-500",
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "science",
    name: "Science",
    icon: Beaker,
    color: "bg-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "maths",
    name: "Maths",
    icon: Calculator,
    color: "bg-violet-500",
    gradient: "from-violet-500 to-purple-600",
  },
  {
    id: "geography",
    name: "Geography",
    icon: Globe,
    color: "bg-cyan-500",
    gradient: "from-cyan-500 to-sky-600",
  },
  {
    id: "history",
    name: "History",
    icon: ScrollText,
    color: "bg-amber-600",
    gradient: "from-amber-600 to-yellow-700",
  },
  {
    id: "civics",
    name: "Civics",
    icon: Users,
    color: "bg-slate-600",
    gradient: "from-slate-600 to-slate-800",
  },
];

function QuestionBankPage() {
  const { user } = useAuth();
  const [selectedClass, setSelectedClass] = useState("1st");
  const [selectedSubjectId, setSelectedSubjectId] = useState(SUBJECTS[0].id);
  const [newQuestion, setNewQuestion] = useState({
    text: "",
    type: "Objective",
    marks: "1",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [searchTerm, setSearchTerm] = useState("");
  const [entriesPerPage, setEntriesPerPage] = useState(10);
  const [currentPage, setCurrentPage] = useState(1);
  const [mounted, setMounted] = useState(false);

  const [questions, setQuestions] = useState<any[]>([]);

  useEffect(() => {
    setMounted(true);
    const q = query(
      collection(db, "question_bank"),
      orderBy("createdAt", "desc"),
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));
      setQuestions(data);
    });

    return () => unsubscribe();
  }, []);

  const handleAddQuestion = async () => {
    if (!newQuestion.text) {
      toast.error("Please enter a question!");
      return;
    }
    setIsSubmitting(true);

    try {
      const newEntry = {
        text: newQuestion.text,
        type: newQuestion.type,
        marks: newQuestion.marks,
        class: selectedClass,
        subjectId: selectedSubjectId,
        createdAt: new Date().toISOString(),
      };

      await addDoc(collection(db, "question_bank"), newEntry);

      setNewQuestion({ text: "", type: "Objective", marks: "1" });
      toast.success("Question added to bank!");
    } catch (error) {
      toast.error("Failed to add question");
    } finally {
      setIsSubmitting(false);
    }
  };

  const deleteQuestion = async (id: string) => {
    try {
      await deleteDoc(doc(db, "question_bank", id));
      toast.info("Question removed.");
    } catch (error) {
      toast.error("Failed to delete question");
    }
  };

  const handleDownload = (unitName: string, subjectId: string) => {
    const subject = SUBJECTS.find((s) => s.id === subjectId)?.name || "Subject";
    const filename = `Question_Bank_${subject}_${unitName.replace(" ", "_")}.pdf`;

    // Simulate PDF download
    const content = `Mock PDF Content for ${subject} ${unitName}\n\nGenerated by Institutional Portal.`;
    const blob = new Blob([content], { type: "application/pdf" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    link.remove();
    toast.success(`${filename} download started!`);
  };

  const filteredData = useMemo(() => {
    return questions.filter((q) => {
      const matchClass = q.class === selectedClass;
      const matchSubject = q.subjectId === selectedSubjectId;
      const matchSearch = q.text
        ?.toLowerCase()
        .includes(searchTerm.toLowerCase());
      return matchClass && matchSubject && matchSearch;
    });
  }, [questions, selectedClass, selectedSubjectId, searchTerm]);

  const totalEntries = filteredData.length;
  const totalPages = Math.ceil(totalEntries / entriesPerPage);
  const paginatedData = filteredData.slice(
    (currentPage - 1) * entriesPerPage,
    currentPage * entriesPerPage,
  );

  const currentSubject =
    SUBJECTS.find((s) => s.id === selectedSubjectId) || SUBJECTS[0];

  return (
    <div className="min-h-screen bg-[#FDFEFF]">
      <TeacherHeader />
      <TeacherSidebar />

      <main className="lg:pl-64 pt-20 min-h-screen bg-white">
        <div className="p-4 md:p-8 space-y-6 max-w-[1200px] mx-auto">
          {/* Top Filter Section */}
          <div className="bg-white p-6 border border-[#dee2e6] rounded-md shadow-sm">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
              <div className="flex flex-col gap-1">
                <label className="text-[13px] font-bold text-[#333]">
                  Class
                </label>
                <select
                  value={selectedClass}
                  onChange={(e) => setSelectedClass(e.target.value)}
                  className="w-full h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px] text-[#555] focus:border-[#66afe9] outline-none bg-white transition-all shadow-inner"
                >
                  <option value="">Select</option>
                  {CLASSES.map((c) => (
                    <option key={c} value={c}>
                      {c}
                    </option>
                  ))}
                </select>
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-[13px] font-bold text-[#333]">
                  Semester
                </label>
                <select className="w-full h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px] text-[#555] focus:border-[#66afe9] outline-none bg-white transition-all shadow-inner">
                  <option value="">Select</option>
                  <option value="1">1st Semester</option>
                  <option value="2">2nd Semester</option>
                </select>
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-[13px] font-bold text-[#333]">
                  Subject
                </label>
                <select
                  value={selectedSubjectId}
                  onChange={(e) => setSelectedSubjectId(e.target.value)}
                  className="w-full h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px] text-[#555] focus:border-[#66afe9] outline-none bg-white transition-all shadow-inner"
                >
                  <option value="">Select</option>
                  {SUBJECTS.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <div className="flex justify-center gap-2">
              <button className="px-3 py-1.5 bg-[#198754] text-white rounded-[4px] text-[14px] font-medium hover:bg-[#157347] transition-all border border-[#198754]">
                Search
              </button>
              <button className="px-3 py-1.5 bg-[#dc3545] text-white rounded-[4px] text-[14px] font-medium hover:bg-[#bb2d3b] transition-all border border-[#dc3545]">
                Reset
              </button>
            </div>
          </div>

          {/* Table Section */}
          <div className="border border-[#dee2e6] rounded-sm overflow-hidden">
            {/* Indigo Heading */}
            <div className="bg-[#3f19c9] px-4 py-2 border-b border-[#dee2e6]">
              <h2 className="text-white font-bold text-[14px]">
                Question Bank With Solution for Common Branches-1st/2nd Semester
              </h2>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse bg-white">
                <thead>
                  <tr className="border-b border-[#dee2e6] text-[#333] text-[14px] font-bold">
                    <th className="px-4 py-2 border-r border-[#dee2e6] w-16">
                      Sr.No.
                    </th>
                    <th className="px-4 py-2 border-r border-[#dee2e6]">
                      Subject / Topic Name
                    </th>
                    <th className="px-4 py-2 border-r border-[#dee2e6]">
                      Type
                    </th>
                    <th className="px-4 py-2 border-r border-[#dee2e6] w-24">
                      Marks
                    </th>
                    <th className="px-4 py-2">Download file</th>
                  </tr>
                </thead>
                <tbody className="text-[14px] text-[#333]">
                  {!mounted ? (
                    <tr>
                      <td colSpan={5} className="px-4 py-10 text-center">
                        Loading...
                      </td>
                    </tr>
                  ) : filteredData.length > 0 ? (
                    filteredData.map((q, idx) => (
                      <tr
                        key={q.id}
                        className="border-b border-[#dee2e6] hover:bg-slate-50"
                      >
                        <td className="px-4 py-2 border-r border-[#dee2e6] text-center text-[#777]">
                          {idx + 1}
                        </td>
                        <td className="px-4 py-2 border-r border-[#dee2e6] text-[#555] font-medium">
                          {q.text}
                        </td>
                        <td className="px-4 py-2 border-r border-[#dee2e6]">
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${q.type === "Objective" ? "bg-blue-100 text-blue-700" : "bg-purple-100 text-purple-700"}`}
                          >
                            {q.type}
                          </span>
                        </td>
                        <td className="px-4 py-2 border-r border-[#dee2e6] text-center font-bold text-slate-600">
                          {q.marks}
                        </td>
                        <td className="px-4 py-2">
                          <button
                            onClick={() =>
                              handleDownload(`Unit ${idx + 1}`, q.subjectId)
                            }
                            className="text-[#3f19c9] hover:underline font-bold"
                          >
                            Unit {idx + 1}
                          </button>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td
                        colSpan={5}
                        className="px-4 py-12 text-center text-[#999] italic"
                      >
                        No records found for the selected criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Minimal Add Form */}
          <div className="bg-white p-6 border border-[#dee2e6] rounded-md shadow-sm">
            <h3 className="text-[16px] font-bold text-[#333] mb-4">
              Add New Record
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <textarea
                value={newQuestion.text}
                onChange={(e) =>
                  setNewQuestion({ ...newQuestion, text: e.target.value })
                }
                className="w-full h-[100px] p-3 border border-[#ccc] rounded-[4px] text-[14px] outline-none focus:border-[#66afe9]"
                placeholder="Enter question/name..."
              />
              <div className="flex flex-col gap-4">
                <div className="grid grid-cols-2 gap-4">
                  <select
                    value={newQuestion.type}
                    onChange={(e) =>
                      setNewQuestion({ ...newQuestion, type: e.target.value })
                    }
                    className="h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px]"
                  >
                    <option value="Objective">Objective</option>
                    <option value="Descriptive">Descriptive</option>
                  </select>
                  <input
                    type="number"
                    value={newQuestion.marks}
                    onChange={(e) =>
                      setNewQuestion({ ...newQuestion, marks: e.target.value })
                    }
                    className="h-[34px] px-3 border border-[#ccc] rounded-[4px] text-[14px]"
                  />
                </div>
                <button
                  onClick={handleAddQuestion}
                  className="h-[40px] bg-[#3f19c9] text-white rounded-[4px] text-[14px] font-bold hover:bg-[#2e12a1] transition-all"
                >
                  Save Record
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
