/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UploaderSignupRouteImport } from './routes/uploader.signup'
import { Route as TeacherTimetableRouteImport } from './routes/teacher.timetable'
import { Route as TeacherTemplatesRouteImport } from './routes/teacher.templates'
import { Route as TeacherTeachingRecordRouteImport } from './routes/teacher.teaching-record'
import { Route as TeacherStatsTeacherRouteImport } from './routes/teacher.stats-teacher'
import { Route as TeacherStatsStudentRouteImport } from './routes/teacher.stats-student'
import { Route as TeacherSqafRouteImport } from './routes/teacher.sqaf'
import { Route as TeacherSqaafRouteImport } from './routes/teacher.sqaaf'
import { Route as TeacherSpecialDayRouteImport } from './routes/teacher.special-day'
import { Route as TeacherSignupRouteImport } from './routes/teacher.signup'
import { Route as TeacherSetupRouteImport } from './routes/teacher.setup'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherResultRouteImport } from './routes/teacher.result'
import { Route as TeacherRecordBookRouteImport } from './routes/teacher.record-book'
import { Route as TeacherQuestionBankRouteImport } from './routes/teacher.question-bank'
import { Route as TeacherPlanningRouteImport } from './routes/teacher.planning'
import { Route as TeacherNoticesRouteImport } from './routes/teacher.notices'
import { Route as TeacherMeetingRouteImport } from './routes/teacher.meeting'
import { Route as TeacherMdmRouteImport } from './routes/teacher.mdm'
import { Route as TeacherLoginRouteImport } from './routes/teacher.login'
import { Route as TeacherHpcCardRouteImport } from './routes/teacher.hpc-card'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as TeacherConceptMappingRouteImport } from './routes/teacher.concept-mapping'
import { Route as TeacherClassSetupRouteImport } from './routes/teacher.class-setup'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentResultRouteImport } from './routes/student.result'
import { Route as StudentQuestionBankRouteImport } from './routes/student.question-bank'
import { Route as StudentNoticesRouteImport } from './routes/student.notices'
import { Route as StudentHomeworkRouteImport } from './routes/student.homework'
import { Route as CoursesCatalogRouteImport } from './routes/courses.catalog'
import { Route as CoursesCatIdRouteImport } from './routes/courses.$catId'
import { Route as AdminWatchersRouteImport } from './routes/admin.watchers'
import { Route as AdminUploadersRouteImport } from './routes/admin.uploaders'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminTeacherDiaryRouteImport } from './routes/admin.teacher-diary'
import { Route as AdminStudentManagementRouteImport } from './routes/admin.student-management'
import { Route as AdminSqafConfigRouteImport } from './routes/admin.sqaf-config'
import { Route as AdminSqaafConfigRouteImport } from './routes/admin.sqaaf-config'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminMeetingTemplatesRouteImport } from './routes/admin.meeting-templates'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminAssemblyRouteImport } from './routes/admin.assembly'
import { Route as AdminAiToolsRouteImport } from './routes/admin.ai-tools'
import { Route as TeacherActivitiesIndexRouteImport } from './routes/teacher.activities.index'
import { Route as TeacherTimetableTeacherRouteImport } from './routes/teacher.timetable.teacher'
import { Route as TeacherTimetableClassRouteImport } from './routes/teacher.timetable.class'
import { Route as TeacherTimetableAssignPeriodRouteImport } from './routes/teacher.timetable.assign-period'
import { Route as TeacherTimetableAssignClassSubjectRouteImport } from './routes/teacher.timetable.assign-class-subject'
import { Route as TeacherTimetableAllRouteImport } from './routes/teacher.timetable.all'
import { Route as TeacherTimetableAddTeacherRouteImport } from './routes/teacher.timetable.add-teacher'
import { Route as TeacherTimetableAddSubjectRouteImport } from './routes/teacher.timetable.add-subject'
import { Route as TeacherTemplatesSportsRouteImport } from './routes/teacher.templates.sports'
import { Route as TeacherTemplatesCulturalRouteImport } from './routes/teacher.templates.cultural'
import { Route as TeacherTemplatesBirthdayRouteImport } from './routes/teacher.templates.birthday'
import { Route as TeacherTemplatesAnnualRouteImport } from './routes/teacher.templates.annual'
import { Route as TeacherTemplatesAdmissionRouteImport } from './routes/teacher.templates.admission'
import { Route as TeacherTemplatesAchievementRouteImport } from './routes/teacher.templates.achievement'
import { Route as TeacherModulesModuleIdRouteImport } from './routes/teacher.modules.$moduleId'
import { Route as TeacherActivitiesCulturalRouteImport } from './routes/teacher.activities.cultural'
import { Route as TeacherActivitiesAnnualRouteImport } from './routes/teacher.activities.annual'
import { Route as SchoolResourceResourceIdRouteImport } from './routes/school.resource.$resourceId'
import { Route as CoursesWatchIdRouteImport } from './routes/courses.watch.$id'
import { Route as AdminUploaderUploaderIdRouteImport } from './routes/admin.uploader.$uploaderId'
import { Route as AdminStudentStudentIdRouteImport } from './routes/admin.student.$studentId'
import { Route as TeacherTemplatesEditTemplateIdRouteImport } from './routes/teacher.templates.edit.$templateId'
import { Route as WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRouteImport } from './routes/webResult.$udiseNumber.$srNo.$academicYear.$classValue.$selectedExamName'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploaderSignupRoute = UploaderSignupRouteImport.update({
  id: '/uploader/signup',
  path: '/uploader/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/teacher/timetable',
  path: '/teacher/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTemplatesRoute = TeacherTemplatesRouteImport.update({
  id: '/teacher/templates',
  path: '/teacher/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeachingRecordRoute = TeacherTeachingRecordRouteImport.update({
  id: '/teacher/teaching-record',
  path: '/teacher/teaching-record',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStatsTeacherRoute = TeacherStatsTeacherRouteImport.update({
  id: '/teacher/stats-teacher',
  path: '/teacher/stats-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStatsStudentRoute = TeacherStatsStudentRouteImport.update({
  id: '/teacher/stats-student',
  path: '/teacher/stats-student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSqafRoute = TeacherSqafRouteImport.update({
  id: '/teacher/sqaf',
  path: '/teacher/sqaf',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSqaafRoute = TeacherSqaafRouteImport.update({
  id: '/teacher/sqaaf',
  path: '/teacher/sqaaf',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSpecialDayRoute = TeacherSpecialDayRouteImport.update({
  id: '/teacher/special-day',
  path: '/teacher/special-day',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSignupRoute = TeacherSignupRouteImport.update({
  id: '/teacher/signup',
  path: '/teacher/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSetupRoute = TeacherSetupRouteImport.update({
  id: '/teacher/setup',
  path: '/teacher/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/teacher/settings',
  path: '/teacher/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherResultRoute = TeacherResultRouteImport.update({
  id: '/teacher/result',
  path: '/teacher/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRecordBookRoute = TeacherRecordBookRouteImport.update({
  id: '/teacher/record-book',
  path: '/teacher/record-book',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherQuestionBankRoute = TeacherQuestionBankRouteImport.update({
  id: '/teacher/question-bank',
  path: '/teacher/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPlanningRoute = TeacherPlanningRouteImport.update({
  id: '/teacher/planning',
  path: '/teacher/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherNoticesRoute = TeacherNoticesRouteImport.update({
  id: '/teacher/notices',
  path: '/teacher/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMeetingRoute = TeacherMeetingRouteImport.update({
  id: '/teacher/meeting',
  path: '/teacher/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMdmRoute = TeacherMdmRouteImport.update({
  id: '/teacher/mdm',
  path: '/teacher/mdm',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherHpcCardRoute = TeacherHpcCardRouteImport.update({
  id: '/teacher/hpc-card',
  path: '/teacher/hpc-card',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/teacher/homework',
  path: '/teacher/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherConceptMappingRoute = TeacherConceptMappingRouteImport.update({
  id: '/teacher/concept-mapping',
  path: '/teacher/concept-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassSetupRoute = TeacherClassSetupRouteImport.update({
  id: '/teacher/class-setup',
  path: '/teacher/class-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/student/timetable',
  path: '/student/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultRoute = StudentResultRouteImport.update({
  id: '/student/result',
  path: '/student/result',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuestionBankRoute = StudentQuestionBankRouteImport.update({
  id: '/student/question-bank',
  path: '/student/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNoticesRoute = StudentNoticesRouteImport.update({
  id: '/student/notices',
  path: '/student/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/student/homework',
  path: '/student/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCatalogRoute = CoursesCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCatIdRoute = CoursesCatIdRouteImport.update({
  id: '/$catId',
  path: '/$catId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminWatchersRoute = AdminWatchersRouteImport.update({
  id: '/admin/watchers',
  path: '/admin/watchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadersRoute = AdminUploadersRouteImport.update({
  id: '/admin/uploaders',
  path: '/admin/uploaders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeacherDiaryRoute = AdminTeacherDiaryRouteImport.update({
  id: '/admin/teacher-diary',
  path: '/admin/teacher-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentManagementRoute = AdminStudentManagementRouteImport.update({
  id: '/admin/student-management',
  path: '/admin/student-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSqafConfigRoute = AdminSqafConfigRouteImport.update({
  id: '/admin/sqaf-config',
  path: '/admin/sqaf-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSqaafConfigRoute = AdminSqaafConfigRouteImport.update({
  id: '/admin/sqaaf-config',
  path: '/admin/sqaaf-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMeetingTemplatesRoute = AdminMeetingTemplatesRouteImport.update({
  id: '/admin/meeting-templates',
  path: '/admin/meeting-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/admin/enrollments',
  path: '/admin/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssemblyRoute = AdminAssemblyRouteImport.update({
  id: '/admin/assembly',
  path: '/admin/assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiToolsRoute = AdminAiToolsRouteImport.update({
  id: '/admin/ai-tools',
  path: '/admin/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherActivitiesIndexRoute = TeacherActivitiesIndexRouteImport.update({
  id: '/teacher/activities/',
  path: '/teacher/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableTeacherRoute = TeacherTimetableTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => TeacherTimetableRoute,
} as any)
const TeacherTimetableClassRoute = TeacherTimetableClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => TeacherTimetableRoute,
} as any)
const TeacherTimetableAssignPeriodRoute =
  TeacherTimetableAssignPeriodRouteImport.update({
    id: '/assign-period',
    path: '/assign-period',
    getParentRoute: () => TeacherTimetableRoute,
  } as any)
const TeacherTimetableAssignClassSubjectRoute =
  TeacherTimetableAssignClassSubjectRouteImport.update({
    id: '/assign-class-subject',
    path: '/assign-class-subject',
    getParentRoute: () => TeacherTimetableRoute,
  } as any)
const TeacherTimetableAllRoute = TeacherTimetableAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => TeacherTimetableRoute,
} as any)
const TeacherTimetableAddTeacherRoute =
  TeacherTimetableAddTeacherRouteImport.update({
    id: '/add-teacher',
    path: '/add-teacher',
    getParentRoute: () => TeacherTimetableRoute,
  } as any)
const TeacherTimetableAddSubjectRoute =
  TeacherTimetableAddSubjectRouteImport.update({
    id: '/add-subject',
    path: '/add-subject',
    getParentRoute: () => TeacherTimetableRoute,
  } as any)
const TeacherTemplatesSportsRoute = TeacherTemplatesSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => TeacherTemplatesRoute,
} as any)
const TeacherTemplatesCulturalRoute =
  TeacherTemplatesCulturalRouteImport.update({
    id: '/cultural',
    path: '/cultural',
    getParentRoute: () => TeacherTemplatesRoute,
  } as any)
const TeacherTemplatesBirthdayRoute =
  TeacherTemplatesBirthdayRouteImport.update({
    id: '/birthday',
    path: '/birthday',
    getParentRoute: () => TeacherTemplatesRoute,
  } as any)
const TeacherTemplatesAnnualRoute = TeacherTemplatesAnnualRouteImport.update({
  id: '/annual',
  path: '/annual',
  getParentRoute: () => TeacherTemplatesRoute,
} as any)
const TeacherTemplatesAdmissionRoute =
  TeacherTemplatesAdmissionRouteImport.update({
    id: '/admission',
    path: '/admission',
    getParentRoute: () => TeacherTemplatesRoute,
  } as any)
const TeacherTemplatesAchievementRoute =
  TeacherTemplatesAchievementRouteImport.update({
    id: '/achievement',
    path: '/achievement',
    getParentRoute: () => TeacherTemplatesRoute,
  } as any)
const TeacherModulesModuleIdRoute = TeacherModulesModuleIdRouteImport.update({
  id: '/teacher/modules/$moduleId',
  path: '/teacher/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherActivitiesCulturalRoute =
  TeacherActivitiesCulturalRouteImport.update({
    id: '/teacher/activities/cultural',
    path: '/teacher/activities/cultural',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherActivitiesAnnualRoute = TeacherActivitiesAnnualRouteImport.update({
  id: '/teacher/activities/annual',
  path: '/teacher/activities/annual',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolResourceResourceIdRoute =
  SchoolResourceResourceIdRouteImport.update({
    id: '/school/resource/$resourceId',
    path: '/school/resource/$resourceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesWatchIdRoute = CoursesWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminUploaderUploaderIdRoute = AdminUploaderUploaderIdRouteImport.update({
  id: '/admin/uploader/$uploaderId',
  path: '/admin/uploader/$uploaderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentStudentIdRoute = AdminStudentStudentIdRouteImport.update({
  id: '/admin/student/$studentId',
  path: '/admin/student/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTemplatesEditTemplateIdRoute =
  TeacherTemplatesEditTemplateIdRouteImport.update({
    id: '/edit/$templateId',
    path: '/edit/$templateId',
    getParentRoute: () => TeacherTemplatesRoute,
  } as any)
const WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute =
  WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRouteImport.update(
    {
      id: '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName',
      path: '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/ai-tools': typeof AdminAiToolsRoute
  '/admin/assembly': typeof AdminAssemblyRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meeting-templates': typeof AdminMeetingTemplatesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sqaaf-config': typeof AdminSqaafConfigRoute
  '/admin/sqaf-config': typeof AdminSqafConfigRoute
  '/admin/student-management': typeof AdminStudentManagementRoute
  '/admin/teacher-diary': typeof AdminTeacherDiaryRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/uploaders': typeof AdminUploadersRoute
  '/admin/watchers': typeof AdminWatchersRoute
  '/courses/$catId': typeof CoursesCatIdRoute
  '/courses/catalog': typeof CoursesCatalogRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/question-bank': typeof StudentQuestionBankRoute
  '/student/result': typeof StudentResultRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/class-setup': typeof TeacherClassSetupRoute
  '/teacher/concept-mapping': typeof TeacherConceptMappingRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/hpc-card': typeof TeacherHpcCardRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/mdm': typeof TeacherMdmRoute
  '/teacher/meeting': typeof TeacherMeetingRoute
  '/teacher/notices': typeof TeacherNoticesRoute
  '/teacher/planning': typeof TeacherPlanningRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/record-book': typeof TeacherRecordBookRoute
  '/teacher/result': typeof TeacherResultRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/setup': typeof TeacherSetupRoute
  '/teacher/signup': typeof TeacherSignupRoute
  '/teacher/special-day': typeof TeacherSpecialDayRoute
  '/teacher/sqaaf': typeof TeacherSqaafRoute
  '/teacher/sqaf': typeof TeacherSqafRoute
  '/teacher/stats-student': typeof TeacherStatsStudentRoute
  '/teacher/stats-teacher': typeof TeacherStatsTeacherRoute
  '/teacher/teaching-record': typeof TeacherTeachingRecordRoute
  '/teacher/templates': typeof TeacherTemplatesRouteWithChildren
  '/teacher/timetable': typeof TeacherTimetableRouteWithChildren
  '/uploader/signup': typeof UploaderSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/student/$studentId': typeof AdminStudentStudentIdRoute
  '/admin/uploader/$uploaderId': typeof AdminUploaderUploaderIdRoute
  '/courses/watch/$id': typeof CoursesWatchIdRoute
  '/school/resource/$resourceId': typeof SchoolResourceResourceIdRoute
  '/teacher/activities/annual': typeof TeacherActivitiesAnnualRoute
  '/teacher/activities/cultural': typeof TeacherActivitiesCulturalRoute
  '/teacher/modules/$moduleId': typeof TeacherModulesModuleIdRoute
  '/teacher/templates/achievement': typeof TeacherTemplatesAchievementRoute
  '/teacher/templates/admission': typeof TeacherTemplatesAdmissionRoute
  '/teacher/templates/annual': typeof TeacherTemplatesAnnualRoute
  '/teacher/templates/birthday': typeof TeacherTemplatesBirthdayRoute
  '/teacher/templates/cultural': typeof TeacherTemplatesCulturalRoute
  '/teacher/templates/sports': typeof TeacherTemplatesSportsRoute
  '/teacher/timetable/add-subject': typeof TeacherTimetableAddSubjectRoute
  '/teacher/timetable/add-teacher': typeof TeacherTimetableAddTeacherRoute
  '/teacher/timetable/all': typeof TeacherTimetableAllRoute
  '/teacher/timetable/assign-class-subject': typeof TeacherTimetableAssignClassSubjectRoute
  '/teacher/timetable/assign-period': typeof TeacherTimetableAssignPeriodRoute
  '/teacher/timetable/class': typeof TeacherTimetableClassRoute
  '/teacher/timetable/teacher': typeof TeacherTimetableTeacherRoute
  '/teacher/activities/': typeof TeacherActivitiesIndexRoute
  '/teacher/templates/edit/$templateId': typeof TeacherTemplatesEditTemplateIdRoute
  '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName': typeof WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/ai-tools': typeof AdminAiToolsRoute
  '/admin/assembly': typeof AdminAssemblyRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meeting-templates': typeof AdminMeetingTemplatesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sqaaf-config': typeof AdminSqaafConfigRoute
  '/admin/sqaf-config': typeof AdminSqafConfigRoute
  '/admin/student-management': typeof AdminStudentManagementRoute
  '/admin/teacher-diary': typeof AdminTeacherDiaryRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/uploaders': typeof AdminUploadersRoute
  '/admin/watchers': typeof AdminWatchersRoute
  '/courses/$catId': typeof CoursesCatIdRoute
  '/courses/catalog': typeof CoursesCatalogRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/question-bank': typeof StudentQuestionBankRoute
  '/student/result': typeof StudentResultRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/class-setup': typeof TeacherClassSetupRoute
  '/teacher/concept-mapping': typeof TeacherConceptMappingRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/hpc-card': typeof TeacherHpcCardRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/mdm': typeof TeacherMdmRoute
  '/teacher/meeting': typeof TeacherMeetingRoute
  '/teacher/notices': typeof TeacherNoticesRoute
  '/teacher/planning': typeof TeacherPlanningRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/record-book': typeof TeacherRecordBookRoute
  '/teacher/result': typeof TeacherResultRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/setup': typeof TeacherSetupRoute
  '/teacher/signup': typeof TeacherSignupRoute
  '/teacher/special-day': typeof TeacherSpecialDayRoute
  '/teacher/sqaaf': typeof TeacherSqaafRoute
  '/teacher/sqaf': typeof TeacherSqafRoute
  '/teacher/stats-student': typeof TeacherStatsStudentRoute
  '/teacher/stats-teacher': typeof TeacherStatsTeacherRoute
  '/teacher/teaching-record': typeof TeacherTeachingRecordRoute
  '/teacher/templates': typeof TeacherTemplatesRouteWithChildren
  '/teacher/timetable': typeof TeacherTimetableRouteWithChildren
  '/uploader/signup': typeof UploaderSignupRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/student/$studentId': typeof AdminStudentStudentIdRoute
  '/admin/uploader/$uploaderId': typeof AdminUploaderUploaderIdRoute
  '/courses/watch/$id': typeof CoursesWatchIdRoute
  '/school/resource/$resourceId': typeof SchoolResourceResourceIdRoute
  '/teacher/activities/annual': typeof TeacherActivitiesAnnualRoute
  '/teacher/activities/cultural': typeof TeacherActivitiesCulturalRoute
  '/teacher/modules/$moduleId': typeof TeacherModulesModuleIdRoute
  '/teacher/templates/achievement': typeof TeacherTemplatesAchievementRoute
  '/teacher/templates/admission': typeof TeacherTemplatesAdmissionRoute
  '/teacher/templates/annual': typeof TeacherTemplatesAnnualRoute
  '/teacher/templates/birthday': typeof TeacherTemplatesBirthdayRoute
  '/teacher/templates/cultural': typeof TeacherTemplatesCulturalRoute
  '/teacher/templates/sports': typeof TeacherTemplatesSportsRoute
  '/teacher/timetable/add-subject': typeof TeacherTimetableAddSubjectRoute
  '/teacher/timetable/add-teacher': typeof TeacherTimetableAddTeacherRoute
  '/teacher/timetable/all': typeof TeacherTimetableAllRoute
  '/teacher/timetable/assign-class-subject': typeof TeacherTimetableAssignClassSubjectRoute
  '/teacher/timetable/assign-period': typeof TeacherTimetableAssignPeriodRoute
  '/teacher/timetable/class': typeof TeacherTimetableClassRoute
  '/teacher/timetable/teacher': typeof TeacherTimetableTeacherRoute
  '/teacher/activities': typeof TeacherActivitiesIndexRoute
  '/teacher/templates/edit/$templateId': typeof TeacherTemplatesEditTemplateIdRoute
  '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName': typeof WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/ai-tools': typeof AdminAiToolsRoute
  '/admin/assembly': typeof AdminAssemblyRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meeting-templates': typeof AdminMeetingTemplatesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sqaaf-config': typeof AdminSqaafConfigRoute
  '/admin/sqaf-config': typeof AdminSqafConfigRoute
  '/admin/student-management': typeof AdminStudentManagementRoute
  '/admin/teacher-diary': typeof AdminTeacherDiaryRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/uploaders': typeof AdminUploadersRoute
  '/admin/watchers': typeof AdminWatchersRoute
  '/courses/$catId': typeof CoursesCatIdRoute
  '/courses/catalog': typeof CoursesCatalogRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/question-bank': typeof StudentQuestionBankRoute
  '/student/result': typeof StudentResultRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/class-setup': typeof TeacherClassSetupRoute
  '/teacher/concept-mapping': typeof TeacherConceptMappingRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/hpc-card': typeof TeacherHpcCardRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/mdm': typeof TeacherMdmRoute
  '/teacher/meeting': typeof TeacherMeetingRoute
  '/teacher/notices': typeof TeacherNoticesRoute
  '/teacher/planning': typeof TeacherPlanningRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/record-book': typeof TeacherRecordBookRoute
  '/teacher/result': typeof TeacherResultRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/setup': typeof TeacherSetupRoute
  '/teacher/signup': typeof TeacherSignupRoute
  '/teacher/special-day': typeof TeacherSpecialDayRoute
  '/teacher/sqaaf': typeof TeacherSqaafRoute
  '/teacher/sqaf': typeof TeacherSqafRoute
  '/teacher/stats-student': typeof TeacherStatsStudentRoute
  '/teacher/stats-teacher': typeof TeacherStatsTeacherRoute
  '/teacher/teaching-record': typeof TeacherTeachingRecordRoute
  '/teacher/templates': typeof TeacherTemplatesRouteWithChildren
  '/teacher/timetable': typeof TeacherTimetableRouteWithChildren
  '/uploader/signup': typeof UploaderSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/student/$studentId': typeof AdminStudentStudentIdRoute
  '/admin/uploader/$uploaderId': typeof AdminUploaderUploaderIdRoute
  '/courses/watch/$id': typeof CoursesWatchIdRoute
  '/school/resource/$resourceId': typeof SchoolResourceResourceIdRoute
  '/teacher/activities/annual': typeof TeacherActivitiesAnnualRoute
  '/teacher/activities/cultural': typeof TeacherActivitiesCulturalRoute
  '/teacher/modules/$moduleId': typeof TeacherModulesModuleIdRoute
  '/teacher/templates/achievement': typeof TeacherTemplatesAchievementRoute
  '/teacher/templates/admission': typeof TeacherTemplatesAdmissionRoute
  '/teacher/templates/annual': typeof TeacherTemplatesAnnualRoute
  '/teacher/templates/birthday': typeof TeacherTemplatesBirthdayRoute
  '/teacher/templates/cultural': typeof TeacherTemplatesCulturalRoute
  '/teacher/templates/sports': typeof TeacherTemplatesSportsRoute
  '/teacher/timetable/add-subject': typeof TeacherTimetableAddSubjectRoute
  '/teacher/timetable/add-teacher': typeof TeacherTimetableAddTeacherRoute
  '/teacher/timetable/all': typeof TeacherTimetableAllRoute
  '/teacher/timetable/assign-class-subject': typeof TeacherTimetableAssignClassSubjectRoute
  '/teacher/timetable/assign-period': typeof TeacherTimetableAssignPeriodRoute
  '/teacher/timetable/class': typeof TeacherTimetableClassRoute
  '/teacher/timetable/teacher': typeof TeacherTimetableTeacherRoute
  '/teacher/activities/': typeof TeacherActivitiesIndexRoute
  '/teacher/templates/edit/$templateId': typeof TeacherTemplatesEditTemplateIdRoute
  '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName': typeof WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/contact'
    | '/courses'
    | '/login'
    | '/mentors'
    | '/pricing'
    | '/profile'
    | '/resources'
    | '/signup'
    | '/upload'
    | '/admin/ai-tools'
    | '/admin/assembly'
    | '/admin/enrollments'
    | '/admin/login'
    | '/admin/meeting-templates'
    | '/admin/reviews'
    | '/admin/sqaaf-config'
    | '/admin/sqaf-config'
    | '/admin/student-management'
    | '/admin/teacher-diary'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/uploaders'
    | '/admin/watchers'
    | '/courses/$catId'
    | '/courses/catalog'
    | '/student/homework'
    | '/student/notices'
    | '/student/question-bank'
    | '/student/result'
    | '/student/timetable'
    | '/teacher/class-setup'
    | '/teacher/concept-mapping'
    | '/teacher/homework'
    | '/teacher/hpc-card'
    | '/teacher/login'
    | '/teacher/mdm'
    | '/teacher/meeting'
    | '/teacher/notices'
    | '/teacher/planning'
    | '/teacher/question-bank'
    | '/teacher/record-book'
    | '/teacher/result'
    | '/teacher/settings'
    | '/teacher/setup'
    | '/teacher/signup'
    | '/teacher/special-day'
    | '/teacher/sqaaf'
    | '/teacher/sqaf'
    | '/teacher/stats-student'
    | '/teacher/stats-teacher'
    | '/teacher/teaching-record'
    | '/teacher/templates'
    | '/teacher/timetable'
    | '/uploader/signup'
    | '/admin/'
    | '/courses/'
    | '/student/'
    | '/teacher/'
    | '/admin/student/$studentId'
    | '/admin/uploader/$uploaderId'
    | '/courses/watch/$id'
    | '/school/resource/$resourceId'
    | '/teacher/activities/annual'
    | '/teacher/activities/cultural'
    | '/teacher/modules/$moduleId'
    | '/teacher/templates/achievement'
    | '/teacher/templates/admission'
    | '/teacher/templates/annual'
    | '/teacher/templates/birthday'
    | '/teacher/templates/cultural'
    | '/teacher/templates/sports'
    | '/teacher/timetable/add-subject'
    | '/teacher/timetable/add-teacher'
    | '/teacher/timetable/all'
    | '/teacher/timetable/assign-class-subject'
    | '/teacher/timetable/assign-period'
    | '/teacher/timetable/class'
    | '/teacher/timetable/teacher'
    | '/teacher/activities/'
    | '/teacher/templates/edit/$templateId'
    | '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/contact'
    | '/login'
    | '/mentors'
    | '/pricing'
    | '/profile'
    | '/resources'
    | '/signup'
    | '/upload'
    | '/admin/ai-tools'
    | '/admin/assembly'
    | '/admin/enrollments'
    | '/admin/login'
    | '/admin/meeting-templates'
    | '/admin/reviews'
    | '/admin/sqaaf-config'
    | '/admin/sqaf-config'
    | '/admin/student-management'
    | '/admin/teacher-diary'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/uploaders'
    | '/admin/watchers'
    | '/courses/$catId'
    | '/courses/catalog'
    | '/student/homework'
    | '/student/notices'
    | '/student/question-bank'
    | '/student/result'
    | '/student/timetable'
    | '/teacher/class-setup'
    | '/teacher/concept-mapping'
    | '/teacher/homework'
    | '/teacher/hpc-card'
    | '/teacher/login'
    | '/teacher/mdm'
    | '/teacher/meeting'
    | '/teacher/notices'
    | '/teacher/planning'
    | '/teacher/question-bank'
    | '/teacher/record-book'
    | '/teacher/result'
    | '/teacher/settings'
    | '/teacher/setup'
    | '/teacher/signup'
    | '/teacher/special-day'
    | '/teacher/sqaaf'
    | '/teacher/sqaf'
    | '/teacher/stats-student'
    | '/teacher/stats-teacher'
    | '/teacher/teaching-record'
    | '/teacher/templates'
    | '/teacher/timetable'
    | '/uploader/signup'
    | '/admin'
    | '/courses'
    | '/student'
    | '/teacher'
    | '/admin/student/$studentId'
    | '/admin/uploader/$uploaderId'
    | '/courses/watch/$id'
    | '/school/resource/$resourceId'
    | '/teacher/activities/annual'
    | '/teacher/activities/cultural'
    | '/teacher/modules/$moduleId'
    | '/teacher/templates/achievement'
    | '/teacher/templates/admission'
    | '/teacher/templates/annual'
    | '/teacher/templates/birthday'
    | '/teacher/templates/cultural'
    | '/teacher/templates/sports'
    | '/teacher/timetable/add-subject'
    | '/teacher/timetable/add-teacher'
    | '/teacher/timetable/all'
    | '/teacher/timetable/assign-class-subject'
    | '/teacher/timetable/assign-period'
    | '/teacher/timetable/class'
    | '/teacher/timetable/teacher'
    | '/teacher/activities'
    | '/teacher/templates/edit/$templateId'
    | '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-tools'
    | '/contact'
    | '/courses'
    | '/login'
    | '/mentors'
    | '/pricing'
    | '/profile'
    | '/resources'
    | '/signup'
    | '/upload'
    | '/admin/ai-tools'
    | '/admin/assembly'
    | '/admin/enrollments'
    | '/admin/login'
    | '/admin/meeting-templates'
    | '/admin/reviews'
    | '/admin/sqaaf-config'
    | '/admin/sqaf-config'
    | '/admin/student-management'
    | '/admin/teacher-diary'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/uploaders'
    | '/admin/watchers'
    | '/courses/$catId'
    | '/courses/catalog'
    | '/student/homework'
    | '/student/notices'
    | '/student/question-bank'
    | '/student/result'
    | '/student/timetable'
    | '/teacher/class-setup'
    | '/teacher/concept-mapping'
    | '/teacher/homework'
    | '/teacher/hpc-card'
    | '/teacher/login'
    | '/teacher/mdm'
    | '/teacher/meeting'
    | '/teacher/notices'
    | '/teacher/planning'
    | '/teacher/question-bank'
    | '/teacher/record-book'
    | '/teacher/result'
    | '/teacher/settings'
    | '/teacher/setup'
    | '/teacher/signup'
    | '/teacher/special-day'
    | '/teacher/sqaaf'
    | '/teacher/sqaf'
    | '/teacher/stats-student'
    | '/teacher/stats-teacher'
    | '/teacher/teaching-record'
    | '/teacher/templates'
    | '/teacher/timetable'
    | '/uploader/signup'
    | '/admin/'
    | '/courses/'
    | '/student/'
    | '/teacher/'
    | '/admin/student/$studentId'
    | '/admin/uploader/$uploaderId'
    | '/courses/watch/$id'
    | '/school/resource/$resourceId'
    | '/teacher/activities/annual'
    | '/teacher/activities/cultural'
    | '/teacher/modules/$moduleId'
    | '/teacher/templates/achievement'
    | '/teacher/templates/admission'
    | '/teacher/templates/annual'
    | '/teacher/templates/birthday'
    | '/teacher/templates/cultural'
    | '/teacher/templates/sports'
    | '/teacher/timetable/add-subject'
    | '/teacher/timetable/add-teacher'
    | '/teacher/timetable/all'
    | '/teacher/timetable/assign-class-subject'
    | '/teacher/timetable/assign-period'
    | '/teacher/timetable/class'
    | '/teacher/timetable/teacher'
    | '/teacher/activities/'
    | '/teacher/templates/edit/$templateId'
    | '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiToolsRoute: typeof AiToolsRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  AdminAiToolsRoute: typeof AdminAiToolsRoute
  AdminAssemblyRoute: typeof AdminAssemblyRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMeetingTemplatesRoute: typeof AdminMeetingTemplatesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSqaafConfigRoute: typeof AdminSqaafConfigRoute
  AdminSqafConfigRoute: typeof AdminSqafConfigRoute
  AdminStudentManagementRoute: typeof AdminStudentManagementRoute
  AdminTeacherDiaryRoute: typeof AdminTeacherDiaryRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminUploadersRoute: typeof AdminUploadersRoute
  AdminWatchersRoute: typeof AdminWatchersRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentNoticesRoute: typeof StudentNoticesRoute
  StudentQuestionBankRoute: typeof StudentQuestionBankRoute
  StudentResultRoute: typeof StudentResultRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  TeacherClassSetupRoute: typeof TeacherClassSetupRoute
  TeacherConceptMappingRoute: typeof TeacherConceptMappingRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherHpcCardRoute: typeof TeacherHpcCardRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  TeacherMdmRoute: typeof TeacherMdmRoute
  TeacherMeetingRoute: typeof TeacherMeetingRoute
  TeacherNoticesRoute: typeof TeacherNoticesRoute
  TeacherPlanningRoute: typeof TeacherPlanningRoute
  TeacherQuestionBankRoute: typeof TeacherQuestionBankRoute
  TeacherRecordBookRoute: typeof TeacherRecordBookRoute
  TeacherResultRoute: typeof TeacherResultRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherSetupRoute: typeof TeacherSetupRoute
  TeacherSignupRoute: typeof TeacherSignupRoute
  TeacherSpecialDayRoute: typeof TeacherSpecialDayRoute
  TeacherSqaafRoute: typeof TeacherSqaafRoute
  TeacherSqafRoute: typeof TeacherSqafRoute
  TeacherStatsStudentRoute: typeof TeacherStatsStudentRoute
  TeacherStatsTeacherRoute: typeof TeacherStatsTeacherRoute
  TeacherTeachingRecordRoute: typeof TeacherTeachingRecordRoute
  TeacherTemplatesRoute: typeof TeacherTemplatesRouteWithChildren
  TeacherTimetableRoute: typeof TeacherTimetableRouteWithChildren
  UploaderSignupRoute: typeof UploaderSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  AdminStudentStudentIdRoute: typeof AdminStudentStudentIdRoute
  AdminUploaderUploaderIdRoute: typeof AdminUploaderUploaderIdRoute
  SchoolResourceResourceIdRoute: typeof SchoolResourceResourceIdRoute
  TeacherActivitiesAnnualRoute: typeof TeacherActivitiesAnnualRoute
  TeacherActivitiesCulturalRoute: typeof TeacherActivitiesCulturalRoute
  TeacherModulesModuleIdRoute: typeof TeacherModulesModuleIdRoute
  TeacherActivitiesIndexRoute: typeof TeacherActivitiesIndexRoute
  WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute: typeof WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploader/signup': {
      id: '/uploader/signup'
      path: '/uploader/signup'
      fullPath: '/uploader/signup'
      preLoaderRoute: typeof UploaderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/teacher/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/templates': {
      id: '/teacher/templates'
      path: '/teacher/templates'
      fullPath: '/teacher/templates'
      preLoaderRoute: typeof TeacherTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/teaching-record': {
      id: '/teacher/teaching-record'
      path: '/teacher/teaching-record'
      fullPath: '/teacher/teaching-record'
      preLoaderRoute: typeof TeacherTeachingRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/stats-teacher': {
      id: '/teacher/stats-teacher'
      path: '/teacher/stats-teacher'
      fullPath: '/teacher/stats-teacher'
      preLoaderRoute: typeof TeacherStatsTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/stats-student': {
      id: '/teacher/stats-student'
      path: '/teacher/stats-student'
      fullPath: '/teacher/stats-student'
      preLoaderRoute: typeof TeacherStatsStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/sqaf': {
      id: '/teacher/sqaf'
      path: '/teacher/sqaf'
      fullPath: '/teacher/sqaf'
      preLoaderRoute: typeof TeacherSqafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/sqaaf': {
      id: '/teacher/sqaaf'
      path: '/teacher/sqaaf'
      fullPath: '/teacher/sqaaf'
      preLoaderRoute: typeof TeacherSqaafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/special-day': {
      id: '/teacher/special-day'
      path: '/teacher/special-day'
      fullPath: '/teacher/special-day'
      preLoaderRoute: typeof TeacherSpecialDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/signup': {
      id: '/teacher/signup'
      path: '/teacher/signup'
      fullPath: '/teacher/signup'
      preLoaderRoute: typeof TeacherSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/setup': {
      id: '/teacher/setup'
      path: '/teacher/setup'
      fullPath: '/teacher/setup'
      preLoaderRoute: typeof TeacherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/teacher/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/result': {
      id: '/teacher/result'
      path: '/teacher/result'
      fullPath: '/teacher/result'
      preLoaderRoute: typeof TeacherResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/record-book': {
      id: '/teacher/record-book'
      path: '/teacher/record-book'
      fullPath: '/teacher/record-book'
      preLoaderRoute: typeof TeacherRecordBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/question-bank': {
      id: '/teacher/question-bank'
      path: '/teacher/question-bank'
      fullPath: '/teacher/question-bank'
      preLoaderRoute: typeof TeacherQuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/planning': {
      id: '/teacher/planning'
      path: '/teacher/planning'
      fullPath: '/teacher/planning'
      preLoaderRoute: typeof TeacherPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/notices': {
      id: '/teacher/notices'
      path: '/teacher/notices'
      fullPath: '/teacher/notices'
      preLoaderRoute: typeof TeacherNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/meeting': {
      id: '/teacher/meeting'
      path: '/teacher/meeting'
      fullPath: '/teacher/meeting'
      preLoaderRoute: typeof TeacherMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/mdm': {
      id: '/teacher/mdm'
      path: '/teacher/mdm'
      fullPath: '/teacher/mdm'
      preLoaderRoute: typeof TeacherMdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/hpc-card': {
      id: '/teacher/hpc-card'
      path: '/teacher/hpc-card'
      fullPath: '/teacher/hpc-card'
      preLoaderRoute: typeof TeacherHpcCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/teacher/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/concept-mapping': {
      id: '/teacher/concept-mapping'
      path: '/teacher/concept-mapping'
      fullPath: '/teacher/concept-mapping'
      preLoaderRoute: typeof TeacherConceptMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/class-setup': {
      id: '/teacher/class-setup'
      path: '/teacher/class-setup'
      fullPath: '/teacher/class-setup'
      preLoaderRoute: typeof TeacherClassSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/student/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/result': {
      id: '/student/result'
      path: '/student/result'
      fullPath: '/student/result'
      preLoaderRoute: typeof StudentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/question-bank': {
      id: '/student/question-bank'
      path: '/student/question-bank'
      fullPath: '/student/question-bank'
      preLoaderRoute: typeof StudentQuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/notices': {
      id: '/student/notices'
      path: '/student/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof StudentNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/student/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/catalog': {
      id: '/courses/catalog'
      path: '/catalog'
      fullPath: '/courses/catalog'
      preLoaderRoute: typeof CoursesCatalogRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$catId': {
      id: '/courses/$catId'
      path: '/$catId'
      fullPath: '/courses/$catId'
      preLoaderRoute: typeof CoursesCatIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/watchers': {
      id: '/admin/watchers'
      path: '/admin/watchers'
      fullPath: '/admin/watchers'
      preLoaderRoute: typeof AdminWatchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uploaders': {
      id: '/admin/uploaders'
      path: '/admin/uploaders'
      fullPath: '/admin/uploaders'
      preLoaderRoute: typeof AdminUploadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teacher-diary': {
      id: '/admin/teacher-diary'
      path: '/admin/teacher-diary'
      fullPath: '/admin/teacher-diary'
      preLoaderRoute: typeof AdminTeacherDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student-management': {
      id: '/admin/student-management'
      path: '/admin/student-management'
      fullPath: '/admin/student-management'
      preLoaderRoute: typeof AdminStudentManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sqaf-config': {
      id: '/admin/sqaf-config'
      path: '/admin/sqaf-config'
      fullPath: '/admin/sqaf-config'
      preLoaderRoute: typeof AdminSqafConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sqaaf-config': {
      id: '/admin/sqaaf-config'
      path: '/admin/sqaaf-config'
      fullPath: '/admin/sqaaf-config'
      preLoaderRoute: typeof AdminSqaafConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meeting-templates': {
      id: '/admin/meeting-templates'
      path: '/admin/meeting-templates'
      fullPath: '/admin/meeting-templates'
      preLoaderRoute: typeof AdminMeetingTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assembly': {
      id: '/admin/assembly'
      path: '/admin/assembly'
      fullPath: '/admin/assembly'
      preLoaderRoute: typeof AdminAssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-tools': {
      id: '/admin/ai-tools'
      path: '/admin/ai-tools'
      fullPath: '/admin/ai-tools'
      preLoaderRoute: typeof AdminAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/activities/': {
      id: '/teacher/activities/'
      path: '/teacher/activities'
      fullPath: '/teacher/activities/'
      preLoaderRoute: typeof TeacherActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/timetable/teacher': {
      id: '/teacher/timetable/teacher'
      path: '/teacher'
      fullPath: '/teacher/timetable/teacher'
      preLoaderRoute: typeof TeacherTimetableTeacherRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/timetable/class': {
      id: '/teacher/timetable/class'
      path: '/class'
      fullPath: '/teacher/timetable/class'
      preLoaderRoute: typeof TeacherTimetableClassRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/timetable/assign-period': {
      id: '/teacher/timetable/assign-period'
      path: '/assign-period'
      fullPath: '/teacher/timetable/assign-period'
      preLoaderRoute: typeof TeacherTimetableAssignPeriodRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/timetable/assign-class-subject': {
      id: '/teacher/timetable/assign-class-subject'
      path: '/assign-class-subject'
      fullPath: '/teacher/timetable/assign-class-subject'
      preLoaderRoute: typeof TeacherTimetableAssignClassSubjectRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/timetable/all': {
      id: '/teacher/timetable/all'
      path: '/all'
      fullPath: '/teacher/timetable/all'
      preLoaderRoute: typeof TeacherTimetableAllRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/timetable/add-teacher': {
      id: '/teacher/timetable/add-teacher'
      path: '/add-teacher'
      fullPath: '/teacher/timetable/add-teacher'
      preLoaderRoute: typeof TeacherTimetableAddTeacherRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/timetable/add-subject': {
      id: '/teacher/timetable/add-subject'
      path: '/add-subject'
      fullPath: '/teacher/timetable/add-subject'
      preLoaderRoute: typeof TeacherTimetableAddSubjectRouteImport
      parentRoute: typeof TeacherTimetableRoute
    }
    '/teacher/templates/sports': {
      id: '/teacher/templates/sports'
      path: '/sports'
      fullPath: '/teacher/templates/sports'
      preLoaderRoute: typeof TeacherTemplatesSportsRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/teacher/templates/cultural': {
      id: '/teacher/templates/cultural'
      path: '/cultural'
      fullPath: '/teacher/templates/cultural'
      preLoaderRoute: typeof TeacherTemplatesCulturalRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/teacher/templates/birthday': {
      id: '/teacher/templates/birthday'
      path: '/birthday'
      fullPath: '/teacher/templates/birthday'
      preLoaderRoute: typeof TeacherTemplatesBirthdayRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/teacher/templates/annual': {
      id: '/teacher/templates/annual'
      path: '/annual'
      fullPath: '/teacher/templates/annual'
      preLoaderRoute: typeof TeacherTemplatesAnnualRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/teacher/templates/admission': {
      id: '/teacher/templates/admission'
      path: '/admission'
      fullPath: '/teacher/templates/admission'
      preLoaderRoute: typeof TeacherTemplatesAdmissionRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/teacher/templates/achievement': {
      id: '/teacher/templates/achievement'
      path: '/achievement'
      fullPath: '/teacher/templates/achievement'
      preLoaderRoute: typeof TeacherTemplatesAchievementRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/teacher/modules/$moduleId': {
      id: '/teacher/modules/$moduleId'
      path: '/teacher/modules/$moduleId'
      fullPath: '/teacher/modules/$moduleId'
      preLoaderRoute: typeof TeacherModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/activities/cultural': {
      id: '/teacher/activities/cultural'
      path: '/teacher/activities/cultural'
      fullPath: '/teacher/activities/cultural'
      preLoaderRoute: typeof TeacherActivitiesCulturalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/activities/annual': {
      id: '/teacher/activities/annual'
      path: '/teacher/activities/annual'
      fullPath: '/teacher/activities/annual'
      preLoaderRoute: typeof TeacherActivitiesAnnualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/resource/$resourceId': {
      id: '/school/resource/$resourceId'
      path: '/school/resource/$resourceId'
      fullPath: '/school/resource/$resourceId'
      preLoaderRoute: typeof SchoolResourceResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/watch/$id': {
      id: '/courses/watch/$id'
      path: '/watch/$id'
      fullPath: '/courses/watch/$id'
      preLoaderRoute: typeof CoursesWatchIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/uploader/$uploaderId': {
      id: '/admin/uploader/$uploaderId'
      path: '/admin/uploader/$uploaderId'
      fullPath: '/admin/uploader/$uploaderId'
      preLoaderRoute: typeof AdminUploaderUploaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student/$studentId': {
      id: '/admin/student/$studentId'
      path: '/admin/student/$studentId'
      fullPath: '/admin/student/$studentId'
      preLoaderRoute: typeof AdminStudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/templates/edit/$templateId': {
      id: '/teacher/templates/edit/$templateId'
      path: '/edit/$templateId'
      fullPath: '/teacher/templates/edit/$templateId'
      preLoaderRoute: typeof TeacherTemplatesEditTemplateIdRouteImport
      parentRoute: typeof TeacherTemplatesRoute
    }
    '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName': {
      id: '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName'
      path: '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName'
      fullPath: '/webResult/$udiseNumber/$srNo/$academicYear/$classValue/$selectedExamName'
      preLoaderRoute: typeof WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesCatIdRoute: typeof CoursesCatIdRoute
  CoursesCatalogRoute: typeof CoursesCatalogRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesWatchIdRoute: typeof CoursesWatchIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCatIdRoute: CoursesCatIdRoute,
  CoursesCatalogRoute: CoursesCatalogRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesWatchIdRoute: CoursesWatchIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface TeacherTemplatesRouteChildren {
  TeacherTemplatesAchievementRoute: typeof TeacherTemplatesAchievementRoute
  TeacherTemplatesAdmissionRoute: typeof TeacherTemplatesAdmissionRoute
  TeacherTemplatesAnnualRoute: typeof TeacherTemplatesAnnualRoute
  TeacherTemplatesBirthdayRoute: typeof TeacherTemplatesBirthdayRoute
  TeacherTemplatesCulturalRoute: typeof TeacherTemplatesCulturalRoute
  TeacherTemplatesSportsRoute: typeof TeacherTemplatesSportsRoute
  TeacherTemplatesEditTemplateIdRoute: typeof TeacherTemplatesEditTemplateIdRoute
}

const TeacherTemplatesRouteChildren: TeacherTemplatesRouteChildren = {
  TeacherTemplatesAchievementRoute: TeacherTemplatesAchievementRoute,
  TeacherTemplatesAdmissionRoute: TeacherTemplatesAdmissionRoute,
  TeacherTemplatesAnnualRoute: TeacherTemplatesAnnualRoute,
  TeacherTemplatesBirthdayRoute: TeacherTemplatesBirthdayRoute,
  TeacherTemplatesCulturalRoute: TeacherTemplatesCulturalRoute,
  TeacherTemplatesSportsRoute: TeacherTemplatesSportsRoute,
  TeacherTemplatesEditTemplateIdRoute: TeacherTemplatesEditTemplateIdRoute,
}

const TeacherTemplatesRouteWithChildren =
  TeacherTemplatesRoute._addFileChildren(TeacherTemplatesRouteChildren)

interface TeacherTimetableRouteChildren {
  TeacherTimetableAddSubjectRoute: typeof TeacherTimetableAddSubjectRoute
  TeacherTimetableAddTeacherRoute: typeof TeacherTimetableAddTeacherRoute
  TeacherTimetableAllRoute: typeof TeacherTimetableAllRoute
  TeacherTimetableAssignClassSubjectRoute: typeof TeacherTimetableAssignClassSubjectRoute
  TeacherTimetableAssignPeriodRoute: typeof TeacherTimetableAssignPeriodRoute
  TeacherTimetableClassRoute: typeof TeacherTimetableClassRoute
  TeacherTimetableTeacherRoute: typeof TeacherTimetableTeacherRoute
}

const TeacherTimetableRouteChildren: TeacherTimetableRouteChildren = {
  TeacherTimetableAddSubjectRoute: TeacherTimetableAddSubjectRoute,
  TeacherTimetableAddTeacherRoute: TeacherTimetableAddTeacherRoute,
  TeacherTimetableAllRoute: TeacherTimetableAllRoute,
  TeacherTimetableAssignClassSubjectRoute:
    TeacherTimetableAssignClassSubjectRoute,
  TeacherTimetableAssignPeriodRoute: TeacherTimetableAssignPeriodRoute,
  TeacherTimetableClassRoute: TeacherTimetableClassRoute,
  TeacherTimetableTeacherRoute: TeacherTimetableTeacherRoute,
}

const TeacherTimetableRouteWithChildren =
  TeacherTimetableRoute._addFileChildren(TeacherTimetableRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiToolsRoute: AiToolsRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  AdminAiToolsRoute: AdminAiToolsRoute,
  AdminAssemblyRoute: AdminAssemblyRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMeetingTemplatesRoute: AdminMeetingTemplatesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSqaafConfigRoute: AdminSqaafConfigRoute,
  AdminSqafConfigRoute: AdminSqafConfigRoute,
  AdminStudentManagementRoute: AdminStudentManagementRoute,
  AdminTeacherDiaryRoute: AdminTeacherDiaryRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminUploadersRoute: AdminUploadersRoute,
  AdminWatchersRoute: AdminWatchersRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentNoticesRoute: StudentNoticesRoute,
  StudentQuestionBankRoute: StudentQuestionBankRoute,
  StudentResultRoute: StudentResultRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  TeacherClassSetupRoute: TeacherClassSetupRoute,
  TeacherConceptMappingRoute: TeacherConceptMappingRoute,
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherHpcCardRoute: TeacherHpcCardRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  TeacherMdmRoute: TeacherMdmRoute,
  TeacherMeetingRoute: TeacherMeetingRoute,
  TeacherNoticesRoute: TeacherNoticesRoute,
  TeacherPlanningRoute: TeacherPlanningRoute,
  TeacherQuestionBankRoute: TeacherQuestionBankRoute,
  TeacherRecordBookRoute: TeacherRecordBookRoute,
  TeacherResultRoute: TeacherResultRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherSetupRoute: TeacherSetupRoute,
  TeacherSignupRoute: TeacherSignupRoute,
  TeacherSpecialDayRoute: TeacherSpecialDayRoute,
  TeacherSqaafRoute: TeacherSqaafRoute,
  TeacherSqafRoute: TeacherSqafRoute,
  TeacherStatsStudentRoute: TeacherStatsStudentRoute,
  TeacherStatsTeacherRoute: TeacherStatsTeacherRoute,
  TeacherTeachingRecordRoute: TeacherTeachingRecordRoute,
  TeacherTemplatesRoute: TeacherTemplatesRouteWithChildren,
  TeacherTimetableRoute: TeacherTimetableRouteWithChildren,
  UploaderSignupRoute: UploaderSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  AdminStudentStudentIdRoute: AdminStudentStudentIdRoute,
  AdminUploaderUploaderIdRoute: AdminUploaderUploaderIdRoute,
  SchoolResourceResourceIdRoute: SchoolResourceResourceIdRoute,
  TeacherActivitiesAnnualRoute: TeacherActivitiesAnnualRoute,
  TeacherActivitiesCulturalRoute: TeacherActivitiesCulturalRoute,
  TeacherModulesModuleIdRoute: TeacherModulesModuleIdRoute,
  TeacherActivitiesIndexRoute: TeacherActivitiesIndexRoute,
  WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute:
    WebResultUdiseNumberSrNoAcademicYearClassValueSelectedExamNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
